on: workflow_dispatch
name: test

jobs:  
  hello:    
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write      
    steps:
      - name: Mon repo lol
        shell: pwsh
        run: |
          gh repo create "repo lol" --private
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
